# Generated by Django 4.2.5 on 2023-10-01 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apps',
            new_name='App',
        ),
    ]
