# Generated by Django 3.2.2 on 2023-10-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=225)),
                ('lastname', models.CharField(max_length=225)),
                ('job_title', models.CharField(max_length=225)),
                ('date_joined', models.DateField(null=True)),
                ('phone', models.BigIntegerField(null=True)),
            ],
        ),
    ]
