# Generated by Django 3.2.2 on 2023-10-03 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='job_title',
            field=models.CharField(default='Team Member', max_length=225),
        ),
    ]
